name: CORE
dependencies:
- python=3.8.12
- numpy=1.19.1
- matplotlib=3.4.3
- networkx=2.8.4
- flask=2.1.3
- pip
- pip:
  - ghhops-server==1.5.3

#if you run " conda env update --prefix ./env --file conda_env.yml  --prune " 
#then it will install pip and ghhops-server without needing to install seperately

# Please install through pip:
# - ghhops-server=1.5.3
# If you use an environment, please first install pip
# Check conda_cheat.txt to install or upgrade pip